[workspace]
resolver = "2"
members = [
  "derive-sql",
  "extras/derive-sql-sqlite",
  "extras/derive-sql-mysql", 
  "extras/derive-sql-common",
  "extras/derive-sql-statement",
  "examples/mona",
]

