[package]
name = "derive-sql-core-from-attributes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn         = { version = "2" }
quote       = "1"
proc-macro2 = "1"

