[package]
name = "derive-sql-common"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2", features = [ "full" ] }
attribute-derive = "0"

