[package]
name = "derive-sql"
version = "0.5.1"
edition = "2021"
license = "MIT"
description = "Structure the interaction with SQL database - currently only SQLite via trait and a procedural macro"
repository = "https://github.com/juliendecharentenay/derive-sql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
# derive-sql-sqlite = { path = "../extras/derive-sql-sqlite", optional = true }
derive-sql-sqlite = { version = "0", optional = true }

[features]
sqlite = [ "derive-sql-sqlite" ]
with-mock = []

[dev-dependencies]
rusqlite = { version = "0", features = [ "chrono" ] }
# derive-sql-sqlite = { path = "../extras/derive-sql-sqlite" }
derive-sql-sqlite = { version = "0" }

