[package]
name = "derive-sql"
version = "0.5.2"
edition = "2021"
license = "MIT"
description = "Structure the interaction with SQL database - currently only SQLite via trait and a procedural macro"
repository = "https://github.com/juliendecharentenay/derive-sql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
derive-sql-sqlite = { version = "0", optional = true }

[features]
default = [ ]
sqlite = [ "derive-sql-sqlite" ]

[package.metadata.docs.rs]
features = [ "sqlite" ]

[dev-dependencies]
mockall = { version = "0" }
